spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: MiClaveSecretaMuyLargaYAlAzar123456789
  expiration-ms: 3600000
